language: php

sudo: true

php:
  - 7.1
  - 7.2

services:
  - mongodb
  - mysql

before_install:
  - composer self-update
  - mysql -e "CREATE SCHEMA test; GRANT ALL PRIVILEGES ON test.* to travis@'%'"
  - pecl install mongodb
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

install:
  - composer update

script:
  - vendor/bin/phpunit

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - pecl uninstall mongodb

cache:
  directories:
    - $HOME/.composer/cache
