language: php

sudo: false

php:
  - 7.1
  - 7.2

env:
  - DB=sqlite
  - DB=mysql
  - DB=mongo

services:
  - mongodb
  - mysql

before_install:
  - composer self-update
  - pecl install mongodb
  - if [[ "$DB" == "mysql" || "$DB" == "mariadb" ]]; then mysql -e "CREATE SCHEMA test; GRANT ALL PRIVILEGES ON test.* to travis@'%'"; fi
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - composer require guzzlehttp/guzzle

install:
  - composer update

script:
  - vendor/bin/phpunit --configuration phpunit.xml --colors --coverage-clover=coverage.clover

after_script:
  - test "5.6" == "${TRAVIS_PHP_VERSION}" && wget https://scrutinizer-ci.com/ocular.phar
  - test -f ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
